# Generated by Django 2.0 on 2020-03-23 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={},
        ),
    ]
