# Generated by Django 2.0 on 2020-03-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0003_auto_20200323_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsid', models.PositiveIntegerField()),
                ('colorid', models.PositiveIntegerField()),
                ('sizeid', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField()),
                ('isdelete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=False, to='userapp.UserInfo')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('goodsid', 'colorid', 'sizeid')},
        ),
    ]
